spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=${database.default_schema}
    username: postgres
    password: fusrodah
    driver-class-name: org.postgresql.Driver